const framed = (name) => `../.generated/frames/${name}-framed.png`;

export const slides = [
  {
    id: "01-one-place",
    theme: "coral",
    kicker: "SNSもWebもAIチャットも",
    title: ["レシピを、", "ひとつに。"],
    layout: "single",
    tilt: -4,
    images: [framed("S__76292201_0")],
  },
  {
    id: "02-url",
    theme: "sun",
    kicker: "気になるレシピをすぐ保存",
    title: ["URLを、", "貼るだけ。"],
    layout: "single",
    tilt: 4,
    images: [framed("S__76292197_0")],
    annotations: [
      {
        screen: 0,
        kind: "ring",
        x: 9,
        y: 64,
        w: 82,
        h: 8,
      },
      {
        screen: 0,
        kind: "note",
        x: 50,
        y: 57,
        text: "ここをタップ",
        arrow: "down",
      },
    ],
  },
  {
    id: "03-share",
    theme: "mint",
    kicker: "SNSからそのまま追加",
    title: ["シェアで、", "すぐ保存。"],
    layout: "single",
    tilt: -4,
    images: [framed("S__76292202")],
    annotations: [
      {
        screen: 0,
        kind: "ring",
        x: 7,
        y: 69,
        w: 25,
        h: 14,
      },
      {
        screen: 0,
        kind: "note",
        x: 56,
        y: 64,
        text: "Foodfolioを選ぶ",
        arrow: "left",
      },
    ],
  },
  {
    id: "04-want-to-cook",
    theme: "coral",
    kicker: "次に作るレシピをまとめて",
    title: ["「作りたい」が、", "すぐ見つかる。"],
    layout: "single",
    tilt: 4,
    images: [framed("S__76292198_0")],
    annotations: [
      {
        screen: 0,
        kind: "ring",
        x: 8,
        y: 55,
        w: 35,
        h: 6,
      },
      {
        screen: 0,
        kind: "note",
        x: 58,
        y: 51,
        text: "作りたい",
        arrow: "left",
      },
    ],
  },
  {
    id: "05-readable",
    theme: "mint",
    kicker: "料理中も迷わない",
    title: ["材料も手順も、", "見やすい。"],
    layout: "duo",
    images: [
      framed("S__76292196_0"),
      framed("S__76292195_0"),
    ],
    labels: ["材料", "作り方"],
  },
  {
    id: "06-unlimited",
    theme: "sun",
    kicker: "保存数を気にしない",
    title: ["好きなだけ、", "保存できる。"],
    layout: "stack",
    images: [
      framed("S__76292199_0"),
      framed("S__76292200_0"),
      framed("S__76292201_0"),
    ],
  },
];

export const sourceAssets = [
  "S__76292195_0.jpg",
  "S__76292196_0.jpg",
  "S__76292197_0.jpg",
  "S__76292198_0.jpg",
  "S__76292199_0.jpg",
  "S__76292200_0.jpg",
  "S__76292201_0.jpg",
  "S__76292202.jpg",
];
