const asset = (name) => `../assets/${name}`;

export const slides = [
  {
    id: "01-one-place",
    theme: "coral",
    eyebrow: "散らばるレシピを、ひとつに",
    title: ["全部ここ。", "もう探さない。"],
    body: ["WebもSNSもAIチャットも。", "見つけたレシピはFoodfolioに集めるだけ。"],
    chips: ["シンプル", "すぐ見つかる"],
    sourceMenu: ["Web", "SNS", "AI Chat", "Foodfolio"],
    layout: "single",
    tilt: -4,
    images: [asset("S__76292201_0.jpg")],
    annotations: [
      {
        screen: 0,
        kind: "note",
        x: 61,
        y: 18,
        text: "作りたい候補が\nひと目でわかる",
        tone: "accent",
        arrow: "down-left",
      },
      {
        screen: 0,
        kind: "ring",
        x: 3,
        y: 23,
        w: 94,
        h: 33,
      },
    ],
  },
  {
    id: "02-url",
    theme: "sun",
    eyebrow: "追加は、びっくりするほど簡単",
    title: ["URL、貼るだけ。", "レシピ完成。"],
    body: ["コピーしたURLを見つけて、", "そのままFoodfolioに追加できます。"],
    chips: ["URLだけ", "入力ほぼゼロ"],
    steps: ["URLをコピー", "Pasteをタップ", "追加完了"],
    layout: "single",
    tilt: 3,
    images: [asset("S__76292197_0.jpg")],
    annotations: [
      {
        screen: 0,
        kind: "ring",
        x: 7,
        y: 65,
        w: 86,
        h: 8,
      },
      {
        screen: 0,
        kind: "note",
        x: 50,
        y: 53,
        text: "ここをタップ",
        tone: "accent",
        arrow: "down",
      },
      {
        screen: 0,
        kind: "tap",
        x: 79,
        y: 69,
        text: "1",
      },
    ],
  },
  {
    id: "03-share",
    theme: "mint",
    eyebrow: "SNSを見ている、その瞬間に",
    title: ["見つけたら、", "その場で保存。"],
    body: ["共有メニューからFoodfolioを選ぶだけ。", "アプリを行ったり来たりしなくてOK。"],
    chips: ["シェア拡張", "SNSから直行"],
    steps: ["共有", "Foodfolio", "保存"],
    layout: "single",
    tilt: -3,
    images: [asset("S__76292202.jpg")],
    annotations: [
      {
        screen: 0,
        kind: "ring",
        x: 5,
        y: 69,
        w: 27,
        h: 14,
      },
      {
        screen: 0,
        kind: "note",
        x: 34,
        y: 66,
        text: "Foodfolioを\nタップするだけ",
        tone: "dark",
        arrow: "left",
      },
      {
        screen: 0,
        kind: "tap",
        x: 18,
        y: 76,
        text: "1",
      },
    ],
  },
  {
    id: "04-want-to-cook",
    theme: "coral",
    eyebrow: "気になるレシピを埋もれさせない",
    title: ["「作りたい」だけ、", "すぐ見つかる。"],
    body: ["あとで作りたいレシピを分けておけるから、", "今日の候補選びがぐっと楽になります。"],
    chips: ["作りたい", "候補を整理"],
    steps: ["気になる", "作りたいに追加", "あとで選ぶ"],
    layout: "single",
    tilt: 4,
    images: [asset("S__76292198_0.jpg")],
    annotations: [
      {
        screen: 0,
        kind: "ring",
        x: 3,
        y: 55,
        w: 38,
        h: 6,
      },
      {
        screen: 0,
        kind: "note",
        x: 43,
        y: 50,
        text: "ここで\n「作りたい」に",
        tone: "accent",
        arrow: "left",
      },
    ],
  },
  {
    id: "05-readable",
    theme: "mint",
    eyebrow: "料理中に欲しい情報だけ",
    title: ["材料も手順も、", "迷わず見える。"],
    body: ["余計な情報に埋もれず、", "作るときに必要なところをすぐ確認。"],
    chips: ["材料", "作り方", "元レシピ"],
    layout: "duo",
    images: [asset("S__76292196_0.jpg"), asset("S__76292195_0.jpg")],
    annotations: [
      {
        screen: 0,
        kind: "note",
        x: 49,
        y: 54,
        text: "材料が\nすっきり",
        tone: "dark",
        arrow: "left",
      },
      {
        screen: 1,
        kind: "note",
        x: 45,
        y: 13,
        text: "手順も\n見やすい",
        tone: "accent",
        arrow: "left",
      },
      {
        screen: 1,
        kind: "ring",
        x: 3,
        y: 16,
        w: 94,
        h: 63,
      },
    ],
  },
  {
    id: "06-unlimited",
    theme: "sun",
    eyebrow: "気に入ったら、どんどん追加",
    title: ["保存数、", "気にしなくていい。"],
    body: ["好きなレシピを好きなだけ。", "あちこちのブックマークを、ひとつの料理帳へ。"],
    chips: ["保存数 無制限", "一か所に集約", "端末間同期"],
    sourceMenu: ["Web", "SNS", "AI Chat", "Foodfolio"],
    layout: "stack",
    images: [
      asset("S__76292199_0.jpg"),
      asset("S__76292200_0.jpg"),
      asset("S__76292201_0.jpg"),
    ],
    annotations: [
      {
        screen: 2,
        kind: "note",
        x: 54,
        y: 24,
        text: "全部まとめて\n自分のレシピ帳に",
        tone: "accent",
        arrow: "down-left",
      },
    ],
  },
];
